name: Docker Image CI-CD

on:
  push:
    branches:    
      - master

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: |
        docker build -t ${{ secrets.REGISTRY_HOST }}/rflap .
        docker login -u ${{ secrets.REGISTRY_USERNAME }} -p ${{ secrets.REGISTRY_PASSWORD }} ${{ secrets.REGISTRY_HOST }}
        docker push ${{ secrets.REGISTRY_HOST }}/rflap